name: Build with Wails v3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4 
        with:
          go-version: '1.24'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=22.0.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev build-essential

      - name: Install Wails v3
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Wails doctor
        run: wails3 doctor

      - name: Install turbo
        run: npm i -g turbo

      - name: Npm install
        run: npm i

      - name: Npm build
        run: npm run build

      - name: Package
        run: |
          cd apps/desktop
          wails3 package

      - uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: ./apps/desktop/bin

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=22.0.0'

      - name: Install Wails v3
        run: go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Install turbo
        run: npm i -g turbo

      - name: Npm installl
        run: npm i

      - name: Npm build
        run: npm run build

      - name: Package
        run: |
          cd apps/desktop
          wails3 package

      - uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: ./apps/desktop/bin
